---
- name: Create custom Ansible fact directory
  file:
    path: "{{ custom_facts_dir }}"
    state: directory

- name: Insert custom fact file
  copy:
    src: "{{ custom_facts_file }}"
    dest: "{{ custom_facts_dir }}/{{ custom_facts_name }}.fact"
    mode: 0755
    owner: "{{ custom_facts_owner }}"
    group: "{{ custom_facts_group }}"
  register: _custom_fact_file_install

- name: Re-run setup to use custom facts
  setup: ~
  when: _custom_fact_file_install.changed
